<?php

namespace AppBundle\Repository;

/**
 * CategorieRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRecetteRepository extends \Doctrine\ORM\EntityRepository
{
}
