<?php

namespace AppBundle\Repository;

/**
 * CategorieIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
