<?php

namespace AppBundle\Repository;

/**
 * EntreePlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreePlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
