<?php

namespace AppBundle\Repository;

/**
 * EntreeListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeListeRepository extends \Doctrine\ORM\EntityRepository
{
}
