<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllIngredients() {
        $qb = $this->createQueryBuilder('i')
            ->leftJoin('i.rayons', 'r')
            ->addSelect('r');

        return $qb->getQuery()->getResult();
    }
}
