<?php

namespace AppBundle\Repository;

/**
 * ListeDeCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeDeCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
