<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercherProduit($caracteres) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
          ->from('AppBundle:Produit', 'p')
          ->where("p.nom LIKE :caracteres")
          ->orderBy('p.nom', 'ASC')
          ->setParameter('caracteres', '%'.$caracteres.'%');

       $query = $qb->getQuery();
       return $query->getResult();
    }

    public function getAllProduits() {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.rayons', 'r')
            ->addSelect('r');

        return $qb->getQuery()->getResult();
    }
}
