<?php

namespace AppBundle\Repository;

/**
 * QuantiteIngredientRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteIngredientRecetteRepository extends \Doctrine\ORM\EntityRepository
{
}
