<?php

namespace AppBundle\Repository;

/**
 * QuantiteIngredientListeDeCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteIngredientListeDeCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
