<?php

namespace AppBundle\Repository;

/**
 * QuantiteProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
