<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * RayonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RayonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListe(User $user) {
        return $this->_em->createQuery('
            SELECT ldc
                 AppBundle:ListeDeCourse ldc,
            WHERE
                ldc.user = :user
            ORDER BY r.nom ASC')
            ->setParameter('user', $user)
            ->getResult();
    }

    public function getIngredients() {
        $qb = $this->createQueryBuilder('r')
            ->join('r.ingredients', 'i')
            ->join('i.rayons' ,'r1')
            ->addSelect('i')
            ->addSelect('r1');

        return $qb->getQuery()->getResult();
    }

    public function getProduits() {
        $qb = $this->createQueryBuilder('r')
            ->join('r.produits', 'p')
            ->join('p.rayons' ,'r1')
            ->addSelect('p')
            ->addSelect('r1');

        return $qb->getQuery()->getResult();
    }
}
