<?php

namespace AppBundle\Repository;

/**
 * TagRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRecetteRepository extends \Doctrine\ORM\EntityRepository
{
}
