<?php

namespace AppBundle\Repository;

/**
 * UniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteRepository extends \Doctrine\ORM\EntityRepository
{
}
