fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    from_email: contact@paul-mesnilgrente.com

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
