# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.form.type.produit_search:
        class: AppBundle\Form\ProduitSearchType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.type.quantite_ingredient_recette:
        class: AppBundle\Form\QuantiteIngredientRecetteType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
