# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    app.left_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", leftMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: left }
    app.right_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", rightMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: right }
